### ISSUE TITLE
converter for hdf5 to adios and vice versa

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-converter#5]
A **tool that converts openPMD files from hdf5 to adios** and vice versa would be useful since:
 - specific pre- and post-processing tool might only work with one or the other
 - some PIC codes (and others) might only have implemented one output format thus this would ease interchange of openPMD files between codes (that only support one version) 

**As an example:**
I have implemented an electron bunch initialization that only works with hdf5 and writes out a openPMD checkpoint that PIConGPU can use to continue simulating the bunch evolution. However since the simulation is quite large and memory consuming, adios would be a better choice for file IO and using hdf5 comes with a performance detriment. Thus, I have right now three options: (1) update my code to the latest `dev` where PIConGPU supports mixed output formats, (2) include adios as output to my pre-processing tool, or (3) convert the generated hdf5 to adios before using PIConGPU with adios only. 

However, since such a conversion tool might be useful for more users, my **question** is whether you @RemiLehe and @ax3l think it is useful too and if you think a conversion between openPMD hdf5 and openPMD adios is possible in general.

**Comment by PrometheusPi** [comment]
Some more questions: 
 - Does such a tool already exist?
 - Would it be better to base such a tool on a general input/output library that supports both formats?

**Comment by ax3l** [comment]
I will be back at work on Monday.

First things first: for one way there are standard tools such as bp2h5 that convert any data, independent of the openPMD markup. You need to compile ADIOS with serial hdf5 support for that but the tool is not too clever (eg memory footprint for large files).

One can implement the same and in both ways of conversion, even chunked for large files, with python scripts. Also here, this can be done agnostic of openPMD markup. Just recursively loop over dirs and copy all attributes and data. I have some scripts doing bp -> h5 already. The other way is just as simple. We can clean and publish them here together if you like.

**Comment by PrometheusPi** [comment]
@ax3l  That sounds great. If a general adios to hdf5 and vice versa conversion is possible and is already implemented, we should definitely use it. Looking forward to Monday.

**Comment by ax3l** [comment]
Great!
Please remind me some can save some hrs for it.

Axel

**Comment by PrometheusPi** [comment]
cc'ing @steindev and @BeyondEspresso (FYI)

**Comment by ax3l** [comment]
Hi,

I just invited you to https://github.com/ax3l/picongpu_data_reduction (private repo) which contains my Titan data reduction and re-processing scripts. Please @ me if you need access and have not gotten it already.

It contains some of the things you are asking for or templates thereof. I would be happy if we adjust some of those to general openPMD for consumption in "this" (`openPMD/openPMD-converter`) repo.

**Comment by ax3l** [comment]
openPMD-api 0.14.0+ ships the `openpmd-pipe` tool (thanks @franzpoeschel), which allows seamless conversion between supported openPMD backends:
https://openpmd-api.readthedocs.io/en/0.14.1/utilities/cli.html#openpmd-pipe

Install:
```bash
python3 -m pip install -U pip
python3 -m pip install -U pipx
python3 -m pipx install -U openpmd-api
```

Usage:
```console
$ openpmd-pipe --help
usage: openpmd-pipe [-h] [--infile INFILE] [--outfile OUTFILE]
                    [--inconfig INCONFIG] [--outconfig OUTCONFIG]

openPMD Pipe.

This tool connects an openPMD-based data source with an openPMD-based data sink
and forwards all data from source to sink.
Possible uses include conversion of data from one backend to another one
or multiplexing the data path in streaming setups.
Parallelization with MPI is optionally possible and is done automatically
as soon as the mpi4py package is found and this tool is called in an MPI
context. In that case, each dataset will be equally sliced along the dimension
with the largest extent.

Examples:
    openpmd-pipe --infile simData.h5 --outfile simData_%T.bp
    openpmd-pipe --infile simData.sst --inconfig @streamConfig.json \
        --outfile simData_%T.bp
    openpmd-pipe --infile uncompressed.bp \
        --outfile compressed.bp --outconfig @compressionConfig.json

optional arguments:
  -h, --help            show this help message and exit
  --infile INFILE       In file
  --outfile OUTFILE     Out file
  --inconfig INCONFIG   JSON config for the in file
  --outconfig OUTCONFIG
                        JSON config for the out file
```

Testing and feedback are very welcome! Please report back under https://github.com/openPMD/openPMD-api for this tool :)
